### ISSUE TITLE
Even when QUALITY is set higher, videos don't download is more than 720p

### ISSUE THREAD

**Issue by JakeShirley** [ErstBlack/youtube_archive#7]
Perhaps I am doing something wrong, but I am using this docker image on my UnRAID server.

Here is how I am setting it up:
<img width="1039" alt="Screen Shot 2020-05-25 at 6 57 46 PM" src="https://user-images.githubusercontent.com/1000311/82853128-abff6000-9eb9-11ea-9a4e-b939994a2b68.png">

Now as far as I know, UnRAID "variables" are just mapped to docker environment variables, so my quality here should be set to 2160p.  For some reason it seems like every one of my videos downloads as 720p.  Any ideas?  Are there any logs that print the command line used or the variables the container is using?

I am on the latest version of the docker container as of May 25, 2020.

**Comment by ErstBlack** [comment]
It might have to do with the FPS in the format string.  Let me know if the update fixes the issue. #8

**Comment by ErstBlack** [comment]
As of right now there aren't any logs in the output.  The best way to check the variables would be to exec into the container and run:
`ps aux`

Would you be able to share one of the channels that you're trying to download so I can try and replicate the issue?

**Comment by JakeShirley** [comment]
Ok!

Here is a channel this is happening with:
https://www.youtube.com/channel/UC6uKrU_WqJ1R2HMTY3LIx5Q

I did just update to the lasted container you just pushed to test as well.

**Comment by JakeShirley** [comment]
Example video:
https://www.youtube.com/watch?v=9fFIzBZ1E0g

Debug output from container:
```
### Environment Variables ###
Archive File: /youtube-directory/archive.txt
Channels File: /youtube-directory/channels.txt
Output Format: video/%(uploader)s [%(channel_id)s]/%(playlist_index)s - %(title)s [%(id)s].%(ext)s
Video UID: 1000
Video GID: 1000
Rate Limit: 5M
Quality: 2160p
Format String: (bestvideo[vcodec^=av01][height=2160][fps>=30]/bestvideo[vcodec=vp9.2][height=2160][fps>=30]/bestvideo[vcodec=vp9][height=2160][fps>=30]/bestvideo[vcodec^=av01][height=2160]/bestvideo[vcodec=vp9.2][height=2160]/bestvideo[vcodec=vp9][height=2160]/bestvideo[height=2160]/bestvideo[vcodec^=av01][height=1440][fps>=30]/bestvideo[vcodec=vp9.2][height=1440][fps>=30]/bestvideo[vcodec=vp9][height=1440][fps>=30]/bestvideo[vcodec^=av01][height=1440]/bestvideo[vcodec=vp9.2][height=1440]/bestvideo[vcodec=vp9][height=1440]/bestvideo[height=1440]/bestvideo[vcodec^=av01][height=1080][fps>=30]/bestvideo[vcodec=vp9.2][height=1080][fps>=30]/bestvideo[vcodec=vp9][height=1080][fps>=30]/bestvideo[vcodec^=av01][height=1080]/bestvideo[vcodec=vp9.2][height=1080]/bestvideo[vcodec=vp9][height=1080]/bestvideo[height=1080]/bestvideo[vcodec^=av01][height=720][fps>=30]/bestvideo[vcodec=vp9.2][height=720][fps>=30]/bestvideo[vcodec=vp9][height=720][fps>=30]/bestvideo[vcodec^=av01][height=720]/bestvideo[vcodec=vp9.2][height=720]/bestvideo[vcodec=vp9][height=720]/bestvideo[height=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best
### End Environment Variables ###
```

**Comment by ErstBlack** [comment]
So it looks like the videos may be reporting themselves as having two separate videos streams, one being 720p and one being 2160p, in your case.

```
PURL                                     : https://www.youtube.com/watch?v=9fFIzBZ1E0g

Video #1
ID                                       : 1
Format                                   : V_MJPEG
Codec ID                                 : V_MJPEG
Duration                                 : 40 ms
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Color space                              : YUV
Default                                  : No
Forced                                   : No
Color range                              : Full
Matrix coefficients                      : BT.470 System B, BT.470 System G

Video #2
ID                                       : 2
Format                                   : VP9
Codec ID                                 : V_VP9
Duration                                 : 1 min 28 s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 (30000/1001) FPS
Color space                              : YUV
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
```

I grabbed this information using mediainfo.  Can you check some of your files and compare?

**Comment by JakeShirley** [comment]
Sorry, new to youtube-dl.  Mind giving me some light instructions on gathering the info you want?  Is `mediainfo` a tool?

**Comment by ErstBlack** [comment]
Yep, you should be able to install it via `apt install mediainfo` or the equivalent.  Then you can run `mediainfo [Your File].mkv` and check the Video section.

You might also be able to use VLC by opening the file in VLC and pressing ctrl+J

**Comment by JakeShirley** [comment]
@ErstBlack ah you're right.  Two streams.
<img width="509" alt="Screen Shot 2020-05-25 at 10 07 07 PM" src="https://user-images.githubusercontent.com/1000311/82862315-2ccb5580-9ed4-11ea-8efa-9ceddd14e386.png">

Any way we could have these output as different files or pick the highest value? I am using Plex to video them and it doesn't seem to live the multiple video streams (unlike IINA and VLC it seems to chose the worse quality one 😄 )

**Comment by ErstBlack** [comment]
I'll take a look and see if I can find a way to filter them out consistently.

**Comment by JakeShirley** [comment]
Thanks a ton @ErstBlack! Love the tool, I run it every night on all of the channels I follow.

**Comment by ErstBlack** [comment]
I pushed an updated container, `docker pull erstblack/youtube_archive:4.0`.  It should remove the extra video stream from any newly downloaded files.
